version: '3.9'
services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
          - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hero
      - POSTGRES_PASSWORD=hello_hero
      - POSTGRES_DB=django_dev_db
      - PGDATA=/var/lib/postgresql/data
volumes:
  postgres_data: